// ─── Global shared state ──────────────────────────────────────────────────────
const state = {
  map: null,
  marker: null,
  sunPathGroup: null,
  moonPathGroup: null,
  keyTimesGroup: null,
  timeIndicatorGroup: null,
  targetGroup: null,
  milkyWayGroup: null,
  finderSourceGroup: null,
  finderBearingLayer: null,
  cardinalGroup: null,
  distanceRingGroup: null,
  fovGroup: null,
  activeTileLayer: null,
  activeLayerName: 'street',
  labelsLayer: null,
  currentLat: null,
  currentLon: null,
  targetLat: null,
  targetLon: null,
  targetMode: false,
  finderSourceLat: null,
  finderSourceLon: null,
  finderSourceMode: false,
  selectedTimezone: '',
  _tzAutoDetected: false,
  dateSliderAnchor: null,
  weather: null,
};
